2022-11-05 13:24:07,747 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Configure stats pid to 7471
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Loading settings from /home/piperunner/.config/wandb/settings
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Loading settings from /home/piperunner/Projects/NTNU/SI/ntnu-si-assignment-3/notebooks/wandb/settings
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'silent': 'true'}
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-05 13:24:07,748 ERROR   MainThread:7471 [wandb_setup.py:_flush():68] [34m[1mwandb[0m: [32m[41mERROR[0m Control-C detected -- Run data was not synced
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:_log_setup():476] Logging user logs to /home/piperunner/Projects/NTNU/SI/ntnu-si-assignment-3/notebooks/wandb/run-20221105_132407-2ri2arz3/logs/debug.log
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:_log_setup():477] Logging internal logs to /home/piperunner/Projects/NTNU/SI/ntnu-si-assignment-3/notebooks/wandb/run-20221105_132407-2ri2arz3/logs/debug-internal.log
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f8dc89a53d0>
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:init():516] calling init triggers
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:init():569] starting backend
2022-11-05 13:24:07,748 INFO    MainThread:7471 [wandb_init.py:init():573] setting up manager
2022-11-05 13:24:07,749 INFO    MainThread:7471 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-05 13:24:07,751 INFO    MainThread:7471 [wandb_init.py:init():580] backend started and connected
2022-11-05 13:24:07,765 INFO    MainThread:7471 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-11-05 13:24:07,765 INFO    MainThread:7471 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-11-05 13:24:07,765 INFO    MainThread:7471 [wandb_init.py:init():658] updated telemetry
2022-11-05 13:24:07,773 INFO    MainThread:7471 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-05 13:24:32,614 WARNING MsgRouterThr:7471 [router.py:message_loop():77] message_loop has been closed
2022-11-05 13:24:32,614 WARNING MsgRouterThr:7471 [router.py:message_loop():77] message_loop has been closed
2022-11-05 13:24:32,615 WARNING MsgRouterThr:7471 [router.py:message_loop():77] message_loop has been closed
2022-11-05 13:24:32,834 ERROR   MainThread:7471 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Configure stats pid to 7471
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Loading settings from /home/piperunner/.config/wandb/settings
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Loading settings from /home/piperunner/Projects/NTNU/SI/ntnu-si-assignment-3/notebooks/wandb/settings
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'silent': 'true'}
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-05 13:25:03,556 ERROR   MainThread:7471 [wandb_setup.py:_flush():68] [34m[1mwandb[0m: [32m[41mERROR[0m Control-C detected -- Run data was not synced
2022-11-05 13:25:03,556 ERROR   MainThread:7471 [wandb_setup.py:_flush():68] [34m[1mwandb[0m: [32m[41mERROR[0m Abnormal program exit
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_init.py:_log_setup():476] Logging user logs to /home/piperunner/Projects/NTNU/SI/ntnu-si-assignment-3/notebooks/wandb/run-20221105_132503-1408bmfc/logs/debug.log
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_init.py:_log_setup():477] Logging internal logs to /home/piperunner/Projects/NTNU/SI/ntnu-si-assignment-3/notebooks/wandb/run-20221105_132503-1408bmfc/logs/debug-internal.log
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_init.py:init():516] calling init triggers
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_init.py:init():569] starting backend
2022-11-05 13:25:03,556 INFO    MainThread:7471 [wandb_init.py:init():573] setting up manager
2022-11-05 13:25:03,568 ERROR   MainThread:7471 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 170, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/piperunner/miniconda3/envs/ntnu-si-assignment-3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
